# Podfile
use_frameworks!
platform :ios, '9.3'

target 'DesafioApps' do
    pod 'RxSwift', '~> 3.3.1'
    pod 'RxCocoa', '~> 3.3.1'
    pod 'Alamofire', '~> 4.4'
    pod 'NibDesignable'
    pod 'Unbox'
    pod 'Moya/RxSwift'
    pod 'Kingfisher'
end

target 'DesafioAppsTests' do
    pod 'RxBlocking', '~> 3.3.1'
    pod 'RxTest', '~> 3.3.1'
    pod 'Moya/RxSwift'
    pod 'Quick'
    pod 'Nimble'
    pod 'Unbox'
end

target 'DesafioAppsUITests' do
    pod 'RxBlocking', '~> 3.3.1'
    pod 'RxTest', '~> 3.3.1'
    pod 'Moya/RxSwift'
    pod 'Quick'
    pod 'Nimble'
    pod 'Unbox'
end
